stages:
  - lint
  - install
  - build_1
  - build_2
  - build_3
  - build_4

python_lint:
  stage: lint
  tags:
    - linux-buildserver
  script:
    - pep8 .

install_octorust:
  stage: install
  tags:
    - linux-buildserver
  script:
    - python setup.py install --user

build_cargo_x86_sample:
  stage: build_1
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/cargo_sample
    - rm ~/.netrc
    - ./cargo_sample.out

build_rustc_x86_sample:
  stage: build_2
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/rustc_sample/rustc_sample.rs
    - rm ~/.netrc
    - ./rustc_sample

build_cargo_x64_sample:
  stage: build_3
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/cargo_sample --architecture x64native
    - rm ~/.netrc
    - qemu-system-x86_64 -serial stdio -smp 8 -numa node -numa node -m 1G -no-reboot -display none -kernel cargo_sample.out

build_rustc_x64_sample:
  stage: build_4
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/rustc_sample/rustc_sample.rs --architecture x64native
    - rm ~/.netrc
    - qemu-system-x86_64 -serial stdio -smp 8 -numa node -numa node -m 1G -no-reboot -display none -kernel rustc_sample
