stages:
  - lint
  - install
  - build

python_lint:
  stage: lint
  tags:
    - linux-buildserver
  script:
    - pep8 .

install_octorust:
  stage: install
  tags:
    - linux-buildserver
  script:
    - python setup.py install --user

build_cargo_x86_sample:
  stage: build
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/cargo_sample
    - rm ~/.netrc
    - ./cargo_sample.out

build_rustc_x86_sample:
  stage: build
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/rustc_sample/rustc_sample.rs
    - rm ~/.netrc
    - ./cargo_sample.out

build_cargo_x64_sample:
  stage: build
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/cargo_sample --architecture x64native
    - rm ~/.netrc
    - ./cargo_sample.out

build_rustc_x64_sample:
  stage: build
  tags:
    - linux-buildserver
  script:
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust samples/rustc_sample/rustc_sample.rs --architecture x64native
    - rm ~/.netrc
    - ./cargo_sample.out