stages:
  - lint
  - install
  - test

python_lint:
  stage: lint
  tags:
    - linux-buildserver
  script:
    - pep8 octorust

install_octorust:
  stage: install
  tags:
    - linux-buildserver
  script:
    - python setup.py install --user
    - echo $NETRC_CREDENTIALS > ~/.netrc
    - octorust -a x86guest --fetch-irtss -i 2017-06-07
    - octorust -a x64native --fetch-irtss -i 2017-06-07
    - octorust -a leon --fetch-irtss -i 2017-06-07
    - rm ~/.netrc

run_applications:
  stage: test
  tags:
    - linux-buildserver
  script:
    - octorust -r -i 2017-06-07 octo-apps/x10_ports/HelloAgent
    - octorust -r -i 2017-06-07 octo-apps/x10_ports/MapReduce
    - octorust -r -i 2017-06-07 octo-apps/experiments/reinvade