[package]
name = "debcompile"
version = "1.0.0"
authors = ["Hermann Krumrey <hermann@krumreyh.com>"]

[dependencies]
core = { path = "deps/libcore" }
libc = { path = "deps/libc", default-features = false }
alloc = { path = "deps/liballoc", default-features = false }