[package]
name = "octolib"
version = "0.1.0"
authors = ["Hermann Krumrey <hermann@krumreyh.com>"]

[dependencies]
core = { path = "deps/libcore" }
libc = { path = "deps/libc", default-features = false }